feat: add Expression type for isTypeOf
sxzz/ast-kit pull request #26
Opened 2024-01-02 08:00 UTC by LoTwT

### Description

This PR is to add `Expression` type for `isTypeOf` by using `isExpression` imported from `@babel/types`.

### Linked Issues

### Additional context

I think it will make `isTypeOf` better to use.

2024-01-04 08:30 UTC, sxzz requested changes
We should not import runtime code from `@babel/types`, since it's a dev dependency. If so, the bundle size will be greatly increased.

2024-01-04 08:33 UTC, LoTwT commented
> We should not import runtime code from `@babel/types`, since it's a dev dependency. If so, the bundle size will be greatly(大大) increased.

Sorry for my rough PR. I'm a newbie on AST-related packages. I will change it with the custom judgment function later.

2024-01-04 09:58 UTC, LoTwT commented
I copy the `isExpression` from `@babel/types` inline the `check.ts`. Is it a better resolution? 🥺

2024-01-04 11:25 UTC, sxzz commented
Let's have a regex expression just like `isFunctionType` function

2024-01-04 15:51 UTC, LoTwT commented
Sorry for my rough PR again. 
I just find there are some other types like `Super`, `JSXElement`, `Literal`s, and so on. 
I think a regex expression may not be able to do it. I will check all the Expression types and find a better way.

2024-01-06 17:42 UTC, sxzz approved these changes

2024-01-06 17:56 UTC, merged